import os
import sys

def run_log_diagnostic(filepath="audit_trace.log"):
    print("==================================================")
    print(" HARM.AI // PIPELINE AUDIT LOG DIAGNOSTIC TOOL ")
    print("==================================================")
    
    if not os.path.exists(filepath):
        print(f"[!] Error: Target file '{filepath}' does not exist on disk.")
        print("    Ensure you ran the BacktestBot redirection command first.")
        return

    # Check file size
    file_size = os.path.getsize(filepath)
    print(f"[*] Target File: {filepath}")
    print(f"[*] File Size  : {file_size} bytes")

    with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()

    line_count = len(lines)
    print(f"[*] Total Lines: {line_count}")
    print("-" * 50)

    if line_count == 0:
        print("[!] Diagnostic: The log file is completely empty.")
        print("    This indicates the Python process crashed before writing a single byte to stdout.")
        print("    Check for immediate syntax, environment, or dependency import errors.")
        return

    # Check for immediate tracebacks or execution crashes
    has_traceback = False
    traceback_lines = []
    for idx, line in enumerate(lines):
        if "Traceback" in line or "Error" in line or "Exception" in line or "SyntaxError" in line:
            has_traceback = True
            traceback_lines.append((idx + 1, line.strip()))

    if has_traceback:
        print("[🚨] CRITICAL CRASH DETECTED IN LOG:")
        for line_num, content in traceback_lines[:5]:
            print(f"    Line {line_num}: {content}")
        print("\n[*] First 15 lines of the crash file for forensic context:")
        for line in lines[:15]:
            print(f"    > {line.strip()}")
        return

    # Check if we are running in quiet/muted logging mode
    sentry_references = [l for l in lines if any(k in l for k in ["Sentry", "Sidekick", "PRODUCER", "SHADOW"])]
    print(f"[*] Pipeline heartbeats found: {len(sentry_references)}")
    
    trade_references = [l for l in lines if any(k in l for k in ["ENTER", "EXIT", "SKIP", "FORCE_CLOSE"])]
    print(f"[*] Transaction activities found: {len(trade_references)}")

    if len(sentry_references) == 0:
        print("\n[!] Diagnostic: Heartbeats are missing entirely.")
        print("    The BacktestBot is running, but your logger level is likely restricting stdout.")
        print("    Let's check the first 5 lines generated by the script:")
        print("-" * 50)
        for line in lines[:5]:
            print(f"    > {line.strip()}")
            
    print("==================================================")

if __name__ == "__main__":
    run_log_diagnostic()
