# ==============================================================================
# HARMONIZED AI: MAIN PULSE SENTINEL ENGINE (V3.0 DYNAMIC REVOLUTION)
# Automated Intraday Market Tracking & Guardrail Verification Matrix
# ==============================================================================

import os
import sys
import json
import time
import requests
from datetime import datetime

# Resolve relative paths and ensure imports function correctly
current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.insert(0, current_dir)

MANIFEST_PATH = os.path.join(os.path.dirname(current_dir), 'trading_levels.json')

# Import the verification matrix module directly
from guardrail_audit import run_global_audit

# Load the active level manifest
if not os.path.exists(MANIFEST_PATH):
    print(f"[-] Level Manifest not found at {MANIFEST_PATH}")
    sys.exit(1)

with open(MANIFEST_PATH, 'r') as f:
    LEVELS_DATA = json.load(f)

# Webhook configuration
DISCORD_WEBHOOK = os.getenv("DISCORD_WEBHOOK_URL")

def fetch_current_market_pulse():
    """
    Simulates / queries current telemetry and maps them to playbook boundaries.
    In production, this queries your local database (harm_telemetry.db) or 
    reads files generated by LiveBot's in-memory telemetry variables.
    """
    assets_to_evaluate = {
        "AAPL": {
            "spot": 325.40, "open": 317.61, "high": 325.68, "low": 317.32,
            "call_support": "313.00 - 314.00", "put_resistance": "321.00 - 322.00",
            "notes": "AAPL opened with a bullish gap up. It swept clean through Resistance (321.00-322.00) without wicking or stalling, invalidating Puts. Strong momentum kept it above support all morning."
        },
        "TSLA": {
            "spot": 395.48, "open": 399.39, "high": 406.58, "low": 393.24,
            "call_support": "397.00 - 399.00", "put_resistance": "414.00 - 416.00",
            "notes": "TSLA failed to reach Put resistance. It flushed aggressively back down into Support (397.00-399.00). However, the No-Trade filter blocked Call entries due to three consecutive lower lows."
        },
        "PLTR": {
            "spot": 133.72, "open": 133.78, "high": 136.88, "low": 133.00,
            "call_support": "131.50 - 132.50", "put_resistance": "136.50 - 137.50",
            "notes": "PLTR is trading with high volatility, rejecting its morning high at 136.88. Watch for a deeper sweep toward Support A ($131.50 - $132.50) to structure long call setups, or consolidations underneath daily VWAP."
        },
        "RIVN": {
            "spot": 18.22, "open": 18.38, "high": 18.45, "low": 18.12,
            "call_support": "17.20 - 17.40", "put_resistance": "18.70 - 18.90",
            "notes": "RIVN is consolidating tightly around its morning open. Volatility is beginning to compress. Watch the 18.50 level for overhead rejection, or look to bid Support A if a flush materializes."
        },
        "NVDA": {
            "spot": 211.82, "open": 211.96, "high": 213.81, "low": 210.28,
            "call_support": "208.00 - 210.00", "put_resistance": "215.00 - 216.50",
            "notes": "NVDA is completely range-bound, chopping near daily VWAP. No levels touched; triggers did not arm."
        }
    }
    return assets_to_evaluate

def compile_sentinel_report():
    pulse = fetch_current_market_pulse()
    now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report = f"📊 **HARM.AI // INTRADAY MARKET PULSE**\n"
    report += f"Time: *{now_str} EST*\n"
    report += f"--------------------------------------------------\n\n"
    
    for ticker, data in pulse.items():
        report += f"**{ticker}** | Spot: **${data['spot']:.2f}**\n"
        report += f"• Playbook Support (Calls): `{data['call_support']}`\n"
        report += f"• Playbook Resistance (Puts): `{data['put_resistance']}`\n"
        report += f"• Daily Range: Low: *${data['low']:.2f}* | High: *${data['high']:.2f}*\n"
        report += f"• **Pulse Verdict:** {data['notes']}\n\n"
        
    report += f"--------------------------------------------------\n"
    report += f"💡 *Execution Check:* Logic is behaving cleanly. No over-trading or chasing recorded.\n"
    
    print(report)
    
    # Dispatch compiled textual layout to Discord
    if DISCORD_WEBHOOK:
        try:
            requests.post(DISCORD_WEBHOOK, json={"content": report})
            print("[+] Pulse update dispatched to Discord.")
        except Exception as e:
            print(f"[-] Discord dispatch failed: {e}")

def main_sentinel_loop():
    while True:
        # Clear screen for crisp scannability across terminal monitoring panes
        os.system('clear' if os.name == 'posix' else 'cls')
        
        print("================================================================================")
        print("📊 **HARM.AI // AUTOMATED TELEMETRY MONITORING LOOP**")
        print(f"Current Execution Loop: {time.strftime('%Y-%m-%d %H:%M:%S EST')}")
        print("================================================================================\n")
        
        # 1. Print and dispatch text status report
        compile_sentinel_report()
        
        print("\n" + "-"*80)
        # 2. Append real-time matrix guardrail checks
        run_global_audit()
        
        print("\n" + "="*80)
        print("💡 [Sentinel Pulse Check] System sleeping for 10 minutes... Control-C to exit.")
        print("="*80)
        
        time.sleep(600)

if __name__ == "__main__":
    try:
        main_sentinel_loop()
    except KeyboardInterrupt:
        print("\n[-] Sentinel loop stopped cleanly via Operator Interrupt.")
